let AllWordLists5 = {
  1: [
    {
      id: "calculator",
      word: "calculator",
      translate: "калькулятор",
      img: "img/5-l1/1.jpg",
    },
    {
      id: "dictionary",
      word: "dictionary",
      translate: "словник",
      img: "img/5-l1/2.jpg",
    },
    {
      id: "laptop",
      word: "laptop",
      translate: "ноутбук",
      img: "img/5-l1/3.jpg",
    },
    {
      id: "map",
      word: "map",
      translate: "карта",
      img: "img/5-l1/4.jpg",
    },
    {
      id: "paints",
      word: "paints",
      translate: "фарби",
      img: "img/5-l1/5.jpg",
    },
    {
      id: "pencil case",
      word: "pencil case",
      translate: "пенал",
      img: "img/5-l1/6.jpg",
    },
    {
      id: "trainers",
      word: "trainers",
      translate: "кросівки",
      img: "img/5-l/7.jpg",
    },
  ],
  2: [
    {
      id: "apples",
      word: "apples",
      translate: "яблука",
      img: "img/5-l2/1.jpg",
    },
    {
      id: "biscuits",
      word: "biscuits",
      translate: "печиво",
      img: "img/5-l2/2.jpg",
    },
    {
      id: "bread",
      word: "bread",
      translate: "хліб",
      img: "img/5-l2/3.jpg",
    },
    {
      id: "cereal",
      word: "cereal",
      translate: "каша",
      img: "img/5-l2/4.jpg",
    },
    {
      id: "сheese",
      word: "cheese",
      translate: "сир",
      img: "img/5-l2/5.jpg",
    },
    {
      id: "сhicken",
      word: "chicken",
      translate: "курка",
      img: "img/5-l2/6.jpg",
    },
    {
      id: "chips",
      word: "chips",
      translate: "чіпси",
      img: "img/5-l2/7.png",
    },
    {
      id: "fish",
      word: "fish",
      translate: "риба",
      img: "img/5-l2/8.jpg",
    },
    {
      id: "fruit",
      word: "fruit",
      translate: "фрукти",
      img: "img/5-l2/9.jpg",
    },
    {
      id: "ham",
      word: "ham",
      translate: "шинка",
      img: "img/5-l2/10.jpg",
    },
    {
      id: "meat",
      word: "meat",
      translate: "м'ясо",
      img: "img/5-l2/11.jpg",
    },
    {
      id: "orange juice",
      word: "orange juice",
      translate: "апельсиновий сік",
      img: "img/5-l2/12.jpg",
    },
    {
      id: "pancakes",
      word: "pancakes",
      translate: "млинці",
      img: "img/5-l2/13.png",
    },
    {
      id: "pasta",
      word: "pasta",
      translate: "макарони",
      img: "img/5-l2/14.jpg",
    },
    {
      id: "potatoes",
      word: "potatoes",
      translate: "картопля",
      img: "img/5-l2/15.jpg",
    },
    {
      id: "rice",
      word: "rice",
      translate: "рис",
      img: "img/5-l2/16.jpg",
    },
    {
      id: "salad",
      word: "salad",
      translate: "салат",
      img: "img/5-l2/17.jpg",
    },
    {
      id: "sandwich",
      word: "sandwich",
      translate: "бутерброд",
      img: "img/5-l2/18.jpg",
    },
    {
      id: "sausages",
      word: "sausages",
      translate: "сосиски",
      img: "img/5-l2/19.jpg",
    },
    {
      id: "tomatoes",
      word: "tomatoes",
      translate: "помідори",
      img: "img/5-l2/20.jpg",
    },
    {
      id: "tuna",
      word: "tuna",
      translate: "тунець",
      img: "img/5-l2/21.jpg",
    },
    {
      id: "vegetables",
      word: "vegetables",
      translate: "овочі",
      img: "img/5-l2/22.jpg",
    },
    {
      id: "water",
      word: "water",
      translate: "вода",
      img: "img/5-l2/23.jpg",
    },
    {
      id: "yoghurt",
      word: "yoghurt",
      translate: "йогурт",
      img: "img/5-l2/24.jpg",
    },
  ],
};
