let AllWordLists2 = {
  1: [
    {
      id: "school",
      word: "school",
      translate: "школа",
      img: "img/2-l1/1.jpg",
    },
    {
      id: "bag",
      word: "bag",
      translate: "портфель",
      img: "img/2-l1/2.jpg",
    },
    {
      id: "pencil",
      word: "pencil",
      translate: "олівець",
      img: "img/2-l1/3.jpg",
    },
    {
      id: "pen",
      word: "pen",
      translate: "ручка",
      img: "img/2-l1/4.jpg",
    },
    {
      id: "rubber",
      word: "rubber",
      translate: "стирачка",
      img: "img/2-l1/5.jpg",
    },
    {
      id: "book",
      word: "book",
      translate: "книжка",
      img: "img/2-l1/6.jpg",
    },
  ],
  2: [
    {
      id: "spell",
      word: "spell",
      translate: "виговорити по буквам (заклинання)",
      img: "img/2-l2/1.gif",
    },
    {
      id: "chair",
      word: "chair",
      translate: "стілець",
      img: "img/2-l2/2.jpg",
    },
    {
      id: "write",
      word: "write",
      translate: "писати",
      img: "img/2-l2/3.gif",
    },
    {
      id: "board",
      word: "board",
      translate: "дошка",
      img: "img/2-l2/4.jpg",
    },
    {
      id: "be quiet",
      word: "be quiet",
      translate: "бути спокійним",
      img: "img/2-l2/5.gif",
    },
  ],
  3: [
    {
      id: "car",
      word: "car",
      translate: "автомобіль",
      img: "img/2-l3/1.gif",
    },
    {
      id: "ball",
      word: "ball",
      translate: "м'яч",
      img: "img/2-l3/2.gif",
    },
    {
      id: "doll",
      word: "doll",
      translate: "лялька",
      img: "img/2-l3/3.jpg",
    },
    {
      id: "stickers",
      word: "stickers",
      translate: "наклейки",
      img: "img/2-l3/4.png",
    },
    {
      id: "crayon",
      word: "crayon",
      translate: "кольоровий олівець",
      img: "img/2-l3/5.jpg",
    },
    {
      id: "сard",
      word: "сard",
      translate: "картка",
      img: "img/2-l3/6.png",
    },
  ],
  4: [
    {
      id: "robot",
      word: "robot",
      translate: "робот",
      img: "img/2-l4/1.gif",
    },
    {
      id: "birthday",
      word: "birthday",
      translate: "день народження",
      img: "img/2-l4/2.gif",
    },
    {
      id: "cake",
      word: "cake",
      translate: "торт",
      img: "img/2-l4/3.gif",
    },
    {
      id: "present",
      word: "present",
      translate: "подарунок",
      img: "img/2-l4/4.gif",
    },
    {
      id: "watch",
      word: "watch",
      translate: "наручний годинник",
      img: "img/2-l4/5.jpg",
    },
    {
      id: "frog",
      word: "frog",
      translate: "жаба",
      img: "img/2-l4/4-1/1.gif",
    },
    {
      id: "teacher",
      word: "teacher",
      translate: "вчителька",
      img: "img/2-l4/4-1/2.gif",
    },
    {
      id: "close",
      word: "close",
      translate: "закрити",
      img: "img/2-l4/4-1/3.jpg",
    },
    {
      id: "door",
      word: "door",
      translate: "двері",
      img: "img/2-l4/4-1/4.gif",
    },
    {
      id: "window",
      word: "window",
      translate: "вікно",
      img: "img/2-l4/4-1/5.jpg",
    },
    {
      id: "stand up",
      word: "stand up",
      translate: "вставати",
      img: "img/2-l4/4-1/6.gif",
    },
    {
      id: "open",
      word: "open",
      translate: "відкрити",
      img: "img/2-l4/4-1/7.gif",
    },
    {
      id: "sit down",
      word: "sit down",
      translate: "сідати",
      img: "img/2-l4/4-1/8.gif",
    },
  ],
  5: [
    {
      id: "sunny",
      word: "sunny",
      translate: "сонячно",
      img: "img/2-l5/1.gif",
    },
    {
      id: "family",
      word: "family",
      translate: "сім'я",
      img: "img/2-l5/2.jpg",
    },
    {
      id: "mum",
      word: "mum",
      translate: "мама",
      img: "img/2-l5/3.jpg",
    },
    {
      id: "dad",
      word: "dad",
      translate: "тато",
      img: "img/2-l5/4.jpg",
    },
    {
      id: "brother",
      word: "brother",
      translate: "брат",
      img: "img/2-l5/5.jpg",
    },
    {
      id: "sister",
      word: "sister",
      translate: "сестра",
      img: "img/2-l5/6.jpg",
    },
  ],

  6: [
    {
      id: "grandpa",
      word: "grandpa",
      translate: "дідусь",
      img: "img/2-l6/1.jpg",
    },
    {
      id: "baby",
      word: "baby",
      translate: "малюк",
      img: "img/2-l6/2.gif",
    },
    {
      id: "boy",
      word: "boy",
      translate: "хлопчик",
      img: "img/2-l6/3.gif",
    },
    {
      id: "girl",
      word: "girl",
      translate: "дівчинка",
      img: "img/2-l6/4.gif",
    },
    {
      id: "grandma",
      word: "grandma",
      translate: "бабуся",
      img: "img/2-l6/5.jpg",
    },
    {
      id: "friend",
      word: "friend",
      translate: "друг/подружка",
      img: "img/2-l6/6.jpg",
    },
  ],
  7: [
    {
      id: "cowboy",
      word: "cowboy",
      translate: "ковбой",
      img: "img/2-l7/1.gif",
    },
    {
      id: "box",
      word: "box",
      translate: "коробка",
      img: "img/2-l7/2.gif",
    },
    {
      id: "сlothes",
      word: "сlothes",
      translate: "одяг",
      img: "img/2-l7/3.gif",
    },
    {
      id: "spy",
      word: "spy",
      translate: "шпіон",
      img: "img/2-l7/4.gif",
    },
    {
      id: "dancer",
      word: "dancer",
      translate: "танцівниця",
      img: "img/2-l7/5.gif",
    },
  ],
  8: [
    {
      id: "pirate",
      word: "pirate",
      translate: "пірат",
      img: "img/2-l8/1.gif",
    },
    {
      id: "clown",
      word: "clown",
      translate: "клоун",
      img: "img/2-l8/2.gif",
    },
    {
      id: "king",
      word: "king",
      translate: "король",
      img: "img/2-l8/3.gif",
    },
    {
      id: "crown",
      word: "crown",
      translate: "корона",
      img: "img/2-l8/4.gif",
    },
    {
      id: "duck",
      word: "duck",
      translate: "кaчка",
      img: "img/2-l8/5.gif",
    },
    {
      id: "happy",
      word: "happy",
      translate: "щасливий",
      img: "img/2-l8/6.jpg",
    },
    {
      id: "small",
      word: "small",
      translate: "малий",
      img: "img/2-l8/7.jpg",
    },
    {
      id: "big",
      word: "big",
      translate: "великий",
      img: "img/2-l8/8.jpg",
    },
    {
      id: "sad",
      word: "sad",
      translate: "сумний",
      img: "img/2-l8/9.png",
    },
    {
      id: "swan",
      word: "swan",
      translate: "лебідь",
      img: "img/2-l8/10.gif",
    },
  ],
  9: [
    {
      id: "kite",
      word: "kite",
      translate: "повітряний змій",
      img: "img/2-l9/1.gif",
    },
    {
      id: "cloudy",
      word: "cloudy",
      translate: "хмарно",
      img: "img/2-l9/2.gif",
    },
    {
      id: "computer game",
      word: "computer game",
      translate: "комп'ютерна гра",
      img: "img/2-l9/3.gif",
    },
    {
      id: "old",
      word: "old",
      translate: "старий",
      img: "img/2-l9/4.png",
    },
    {
      id: "radio",
      word: "radio",
      translate: "радіо",
      img: "img/2-l9/5.gif",
    },
    {
      id: "new",
      word: "new",
      translate: "новий",
      img: "img/2-l9/6.jpg",
    },
    {
      id: "bike",
      word: "bike",
      translate: "велосипед",
      img: "img/2-l9/7.gif",
    },
  ],
  10: [
    {
      id: "toys",
      word: "toys",
      translate: "іграшки",
      img: "img/2-10/1.jpg",
    },
    {
      id: "rollerblades",
      word: "rollerblades",
      translate: "ролики",
      img: "img/2-l10/2.jpg",
    },
    {
      id: "train",
      word: "train",
      translate: "поїзд",
      img: "img/2-l10/3.gif",
    },
    {
      id: "slow",
      word: "slow",
      translate: "повільний",
      img: "img/2-l10/4.jpg",
    },
    {
      id: "fast",
      word: "fast",
      translate: "швидкий",
      img: "img/2-l10/5.jpg",
    },
    {
      id: "winner",
      word: "winner",
      translate: "переможець",
      img: "img/2-l10/6.jpg",
    },
    {
      id: "prize",
      word: "prize",
      translate: "приз",
      img: "img/2-l10/7.gif",
    },
  ],
  12: [
    {
      id: "circus",
      word: "circus",
      translate: "цирк",
      img: "img/2-l12/1.gif",
    },
    {
      id: "funny",
      word: "funny",
      translate: "веселий",
      img: "img/2-l12/2.gif",
    },
    {
      id: "long",
      word: "long",
      translate: "довгий",
      img: "img/2-l12/3.jpg",
    },
    {
      id: "short",
      word: "short",
      translate: "короткий",
      img: "img/2-l12/4.jpg",
    },
    {
      id: "strong",
      word: "strong",
      translate: "сильний",
      img: "img/2-l12/5.gif",
    },
    {
      id: "trunk",
      word: "trunk",
      translate: "хобот",
      img: "img/2-l12/6.gif",
    },
    {
      id: "star",
      word: "star",
      translate: "зірка",
      img: "img/2-l12/7.gif",
    },
  ],
  14: [
    {
      id: "hot",
      word: "hot",
      translate: "спекотно",
      img: "img/2-l14/1.gif",
    },
    {
      id: "treehouse",
      word: "treehouse",
      translate: "будинок на дереві",
      img: "img/2-l14/2.jpg",
    },
    {
      id: "shop",
      word: "shop",
      translate: "магазин",
      img: "img/2-l14/3.gif",
    },
    {
      id: "swing",
      word: "swing",
      translate: "гойдалки",
      img: "img/2-l14/4.gif",
    },
    {
      id: "slide",
      word: "slide",
      translate: "похила площина",
      img: "img/2-l14/5.gif",
    },
    {
      id: "climbing frame",
      word: "climbing frame",
      translate: "скелелазіння",
      img: "img/2-l14/6.jpg",
    },
    {
      id: "bus",
      word: "bus",
      translate: "автобус",
      img: "img/2-l14/7.gif",
    },
  ],
  15: [
    {
      id: "sing",
      word: "sing",
      translate: "співати",
      img: "img/2-l15/1.gif",
    },
    {
      id: "jump",
      word: "jump",
      translate: "стрибати",
      img: "img/2-l15/2.gif",
    },
    {
      id: "high",
      word: "high",
      translate: "високий",
      img: "img/2-l15/3.jpg",
    },
    {
      id: "ride",
      word: "ride",
      translate: "їздити",
      img: "img/2-l15/4.gif",
    },
    {
      id: "swim",
      word: "swim",
      translate: "плавати",
      img: "img/2-l15/5.gif",
    },
    {
      id: "сlimb",
      word: "climb",
      translate: "підйом",
      img: "img/2-l15/6.gif",
    },
    {
      id: "play the guitar",
      word: "play the guitar",
      translate: "грати на гітарі",
      img: "img/2-l15/7.gif",
    },
  ],
  16: [
    {
      id: "skip",
      word: "skip",
      translate: "перескочити",
      img: "img/2-l16/1.gif",
    },
    {
      id: "rollerblade",
      word: "rollerblade",
      translate: "ролики",
      img: "img/2-l16/2.gif",
    },
    {
      id: "fly",
      word: "fly",
      translate: "літати",
      img: "img/2-l16/3.gif",
    },
    {
      id: "do a handstand",
      word: "do a handstand",
      translate: "зробити стійку на руках",
      img: "img/2-l16/4.gif",
    },
    {
      id: "walk",
      word: "walk",
      translate: "гуляти",
      img: "img/2-l16/5.gif",
    },
    {
      id: "run",
      word: "run",
      translate: "бігти",
      img: "img/2-l16/6.gif",
    },
    {
      id: "carry",
      word: "carry",
      translate: "нести",
      img: "img/2-l16/7.gif",
    },
  ],
  17: [
    {
      id: "mobile phone",
      word: "mobile phone",
      translate: "мобільний телефон",
      img: "img/2-l17/1.gif",
    },
    {
      id: "desk",
      word: "desk",
      translate: "парта",
      img: "img/2-l17/2.jpg",
    },
    {
      id: "cupboard",
      word: "cupboard",
      translate: "шафа",
      img: "img/2-l17/3.gif",
    },
    {
      id: "computer",
      word: "computer",
      translate: "комп'ютер",
      img: "img/2-l17/4.gif",
    },
    {
      id: "bookcase",
      word: "bookcase",
      translate: "книжкова шафа",
      img: "img/2-l17/5.jpg",
    },
    {
      id: "table",
      word: "table",
      translate: "стіл",
      img: "img/2-l17/6.gif",
    },
    {
      id: "bed",
      word: "bed",
      translate: "ліжко",
      img: "img/2-l17/7.gif",
    },
  ],
  21: [
    {
      id: "play",
      word: "play",
      translate: "гратися",
      img: "img/2-l21/1.gif",
    },
    {
      id: "read",
      word: "read",
      translate: "читати",
      img: "img/2-l21/2.gif",
    },
    {
      id: "sleep",
      word: "sleep",
      translate: "спати",
      img: "img/2-l21/3.gif",
    },
    {
      id: "hide",
      word: "hide",
      translate: "ховатися",
      img: "img/2-l21/4.gif",
    },
    {
      id: "water pistol",
      word: "water pistol",
      translate: "водний пістолет",
      img: "img/2-l21/5.gif",
    },
    {
      id: "come",
      word: "come",
      translate: "приходити",
      img: "img/2-l21/6.gif",
    },
  ],
  22: [
    {
      id: "have a shower",
      word: "have a shower",
      translate: "приймати душ",
      img: "img/2-l22/1.gif",
    },
    {
      id: "trousers",
      word: "trousers",
      translate: "штани",
      img: "img/2-l22/2.png",
    },
    {
      id: "T-shirt",
      word: "T-shirt",
      translate: "футболка",
      img: "img/2-l22/3.png",
    },
    {
      id: "shoes",
      word: "shoes",
      translate: "взуття",
      img: "img/2-l22/4.gif",
    },
    {
      id: "skirt",
      word: "skirt",
      translate: "спідниця",
      img: "img/2-l22/5.jpg",
    },
    {
      id: "dress",
      word: "dress",
      translate: "сукня",
      img: "img/2-l22/6.gif",
    },
    {
      id: "sweater",
      word: "sweater",
      translate: "светр",
      img: "img/2-l22/7.gif",
    },
  ],
  23: [
    {
      id: "basketball",
      word: "basketball",
      translate: "баскетбол",
      img: "img/2-l23/1.gif",
    },
    {
      id: "volleyball",
      word: "volleyball",
      translate: "волейбол",
      img: "img/2-l23/2.gif",
    },
    {
      id: "football",
      word: "football",
      translate: "футбол",
      img: "img/2-l23/3.gif",
    },
    {
      id: "tennis",
      word: "tennis",
      translate: "теніс",
      img: "img/2-l23/4.gif",
    },
    {
      id: "idea",
      word: "idea",
      translate: "ідея",
      img: "img/2-l23/5.gif",
    },
    {
      id: "tired",
      word: "tired",
      translate: "втомлений",
      img: "img/2-l23/6.gif",
    },
  ],
  24: [
    {
      id: "dream",
      word: "dream",
      translate: "coн",
      img: "img/2-l24/1.gif",
    },
    {
      id: "noise",
      word: "noise",
      translate: "шум",
      img: "img/2-l24/2.gif",
    },
    {
      id: "eat",
      word: "eat",
      translate: "їсти",
      img: "img/2-l24/3.gif",
    },
    {
      id: "drink",
      word: "drink",
      translate: "пити",
      img: "img/2-l24/4.gif",
    },
    {
      id: "upstairs",
      word: "upstairs",
      translate: "нагорі",
      img: "img/2-l24/5.gif",
    },
    {
      id: "roar",
      word: "roar",
      translate: "рев",
      img: "img/2-l24/6.gif",
    },
    {
      id: "snore",
      word: "snore",
      translate: "хропіти",
      img: "img/2-l24/7.gif",
    },
  ],
  25: [
    {
      id: "crab",
      word: "crab",
      translate: "краб",
      img: "img/2-l25/1.gif",
    },
    {
      id: "raining",
      word: "raining",
      translate: "дощ",
      img: "img/2-l25/2.gif",
    },
    {
      id: "dolphin",
      word: "dolphin",
      translate: "дельфін",
      img: "img/2-l25/3.gif",
    },
    {
      id: "turtle",
      word: "turtle",
      translate: "черепаха",
      img: "img/2-l25/4.gif",
    },
    {
      id: "сamera",
      word: "сamera",
      translate: "камера",
      img: "img/2-l25/5.gif",
    },
    {
      id: "take a photo",
      word: "take a photo",
      translate: "сфотографувати",
      img: "img/2-l25/6.gif",
    },
  ],
  26: [
    {
      id: "men",
      word: "men",
      translate: "чоловік",
      img: "img/2-l26/1.gif",
    },
    {
      id: "feed",
      word: "feed",
      translate: "годувати",
      img: "img/2-l26/2.gif",
    },
    {
      id: "women",
      word: "women",
      translate: "жінка",
      img: "img/2-l26/3.gif",
    },
    {
      id: "tall",
      word: "tall",
      translate: "високий",
      img: "img/2-l26/4.gif",
    },
    {
      id: "shark",
      word: "shark",
      translate: "акула",
      img: "img/2-l26/5.gif",
    },
    {
      id: "teeth",
      word: "teeth",
      translate: "зуби",
      img: "img/2-l26/6.gif",
    },
  ],
  27: [
    {
      id: "bowl",
      word: "bowl",
      translate: "чаша",
      img: "img/2-l27/1.gif",
    },
    {
      id: "carrot",
      word: "carrot",
      translate: "морква",
      img: "img/2-l27/2.gif",
    },
    {
      id: "drawer",
      word: "drawer",
      translate: "шухляда",
      img: "img/2-l27/3.gif",
    },
    {
      id: "shelf",
      word: "shelf",
      translate: "полиця",
      img: "img/2-l27/4.jpg",
    },
    {
      id: "cherry",
      word: "cherry",
      translate: "вишня",
      img: "img/2-l27/5.gif",
    },
    {
      id: "sweets",
      word: "sweets",
      translate: "солодощі",
      img: "img/2-l27/6.gif",
    },
    {
      id: "chocolate",
      word: "chocolate",
      translate: "шоколад",
      img: "img/2-l27/7.gif",
    },
  ],
  28: [
    {
      id: "forest",
      word: "forest",
      translate: "ліс",
      img: "img/2-l28/1.gif",
    },
    {
      id: "biscuit",
      word: "biscuit",
      translate: "печиво",
      img: "img/2-l28/2.gif",
    },
    {
      id: "wall",
      word: "wall",
      translate: "стіна",
      img: "img/2-l28/3.gif",
    },
    {
      id: "little",
      word: "little",
      translate: "маленький",
      img: "img/2-l28/4.gif",
    },
    {
      id: "squirrel",
      word: "squirrel",
      translate: "білка",
      img: "img/2-l28/5.gif",
    },
    {
      id: "angry",
      word: "angry",
      translate: "злий",
      img: "img/2-l28/6.gif",
    },
  ],
};

let AllWordLists4 = {
  1: [
    {
      id: "clever",
      word: "clever",
      translate: "розумний",
      img: "img/4-l1/1.gif",
    },
    {
      id: "niece",
      word: "niece",
      translate: "племінниця",
      img: "img/4-l1/2.jpg",
    },
    {
      id: "nephew",
      word: "nephew",
      translate: "племінник",
      img: "img/4-l1/3.jpg",
    },
    {
      id: "friendly",
      word: "friendly",
      translate: "дружелюбний",
      img: "img/4-l1/4.gif",
    },
    {
      id: "helpful",
      word: "helpful",
      translate: "корисний",
      img: "img/4-l1/5-1.jpg",
    },
  ],
  2: [
    {
      id: "laptop",
      word: "laptop",
      translate: "ноутбук",
      img: "img/4-l2/1.jpg",
    },
    {
      id: "binoculars",
      word: "binoculars",
      translate: "бінокль",
      img: "img/4-l2/2.jpg",
    },
    {
      id: "compass",
      word: "compass",
      translate: "компас",
      img: "img/4-l2/3.jpg",
    },
    {
      id: "can opener",
      word: "can opener",
      translate: "консервний ніж",
      img: "img/4-l2/4.jpg",
    },
    {
      id: "diary",
      word: "diary",
      translate: "щоденник",
      img: "img/4-l2/6.jpg",
    },
    {
      id: "torch",
      word: "torch",
      translate: "фонарик",
      img: "img/4-l2/7.jpg",
    },
  ],
  3: [
    {
      id: "well",
      word: "well",
      translate: "добре",
      img: "img/4-l3/1.png",
    },
    {
      id: "carefully",
      word: "carefully",
      translate: "обережно",
      img: "img/4-l3/2.jpg",
    },
    {
      id: "badly",
      word: "badly",
      translate: "погано",
      img: "img/4-l3/3.jpg",
    },
    {
      id: "slowly",
      word: "slowly",
      translate: "повільно",
      img: "img/4-l3/4.jpg",
    },
    {
      id: "quietly",
      word: "quietly",
      translate: "тихо",
      img: "img/4-l3/5.jpg",
    },
    {
      id: "happily",
      word: "happily",
      translate: "щасливо",
      img: "img/4-l3/6.jpg",
    },
    {
      id: "quickly",
      word: "quickly",
      translate: "швидко",
      img: "img/4-l3/6-1.jpg",
    },
  ],
  5: [
    {
      id: "storm",
      word: "storm",
      translate: "шторм",
      img: "img/4-l5/1.gif",
    },
    {
      id: "behind",
      word: "behind",
      translate: "позаду",
      img: "img/4-l5/2.jpg",
    },
    {
      id: "windy",
      word: "windy",
      translate: "вітряно",
      img: "img/4-l5/3.gif",
    },
    {
      id: "thunder",
      word: "thunder",
      translate: "грім",
      img: "img/4-l5/4.gif",
    },
    {
      id: "in front of",
      word: "in front of",
      translate: "попереду",
      img: "img/4-l5/5.jpg",
    },
    {
      id: "lightning",
      word: "lightning",
      translate: "блискавка",
      img: "img/4-l5/6.gif",
    },
  ],
  6: [
    {
      id: "aquarium",
      word: "aquarium",
      translate: "акваріум",
      img: "img/4-l6/1.gif",
    },
    {
      id: "town hall",
      word: "town hall",
      translate: "мерія",
      img: "img/4-l6/2.jpg",
    },
    {
      id: "police station",
      word: "police station",
      translate: "відділення міліції",
      img: "img/4-l6/3.jpg",
    },
    {
      id: "pet shop",
      word: "pet shop",
      translate: "зоомагазин",
      img: "img/4-l6/4.jpg",
    },
    {
      id: "museum",
      word: "museum",
      translate: "музей",
      img: "img/4-l6/5.jpg",
    },
    {
      id: "cafe",
      word: "cafe",
      translate: "кафе",
      img: "img/4-l6/6.jpg",
    },
  ],
  7: [
    {
      id: "notice",
      word: "notice",
      translate: "помічати",
      img: "img/4-l7/1.gif",
    },
    {
      id: "blond",
      word: "blond",
      translate: "блондин",
      img: "img/4-l7/2.jpg",
    },
    {
      id: "mustache",
      word: "mustache",
      translate: "вуса",
      img: "img/4-l7/3.jpg",
    },
    {
      id: "beard",
      word: "beard",
      translate: "борода",
      img: "img/4-l7/4.gif",
    },
    {
      id: "thin",
      word: "thin",
      translate: "худий",
      img: "img/4-l7/5.gif",
    },
    {
      id: "curly",
      word: "curly",
      translate: "кучерявий",
      img: "img/4-l7/6.png",
    },
    {
      id: "face",
      word: "face",
      translate: "обличчя",
      img: "img/4-l7/7.gif",
    },
  ],
  9: [
    {
      id: "farm",
      word: "farm",
      translate: "ферма",
      img: "img/4-l9/1.gif",
    },
    {
      id: "cow",
      word: "cow",
      translate: "корова",
      img: "img/4-l9/2.jpg",
    },
    {
      id: "grass",
      word: "grass",
      translate: "трава",
      img: "img/4-l9/3.gif",
    },
    {
      id: "owl",
      word: "owl",
      translate: "сова",
      img: "img/4-l9/4.gif",
    },
    {
      id: "pond",
      word: "pond",
      translate: "ставок",
      img: "img/4-l9/5.gif",
    },
    {
      id: "bull",
      word: "bull",
      translate: "бик",
      img: "img/4-l9/6.png",
    },
  ],
  10: [
    {
      id: "scared",
      word: "scared",
      translate: "наляканий",
      img: "img/4-l10/1-2.gif",
    },
    {
      id: "confused",
      word: "confused",
      translate: "розгублений",
      img: "img/4-l10/2.gif",
    },
    {
      id: "nervous",
      word: "nervous",
      translate: "нервовий",
      img: "img/4-l10/3.gif",
    },
    {
      id: "unhappy",
      word: "unhappy",
      translate: "нещасний",
      img: "img/4-l10/4.gif",
    },
  ],
  11: [
    {
      id: "well",
      word: "well",
      translate: "здоровий",
      img: "img/4-l11/1.gif",
    },
    {
      id: "сold",
      word: "сold",
      translate: "змерзлий",
      img: "img/4-l11/2.gif",
    },
    {
      id: "headache",
      word: "headache",
      translate: "головний біль",
      img: "img/4-l11/3.jpg",
    },
    {
      id: "sore throat",
      word: "sore throat",
      translate: "біль у горлі",
      img: "img/4-l11/4.jpg",
    },
    {
      id: "earache",
      word: "earache",
      translate: "біль у вусі",
      img: "img/4-l11/5.jpg",
    },
    {
      id: "ill",
      word: "ill",
      translate: "хворий",
      img: "img/4-l11/6.gif",
    },
    {
      id: "stomachache",
      word: "stomachache",
      translate: "біль у животі",
      img: "img/4-l11/7.png",
    },
  ],
  13: [
    {
      id: "train station",
      word: "train station",
      translate: "зупинка поїзда",
      img: "img/4-l13/1.jpg",
    },
    {
      id: "road",
      word: "road",
      translate: "дорога",
      img: "img/4-l13/2.gif",
    },
    {
      id: "market",
      word: "market",
      translate: "базар",
      img: "img/4-l13/3.gif",
    },
    {
      id: "сastle",
      word: "сastle",
      translate: "замок",
      img: "img/4-l13/4.png",
    },
    {
      id: "bridge",
      word: "bridge",
      translate: "міст",
      img: "img/4-l13/5.jpg",
    },
  ],
  15: [
    {
      id: "stew",
      word: "stew",
      translate: "рагу",
      img: "img/4-l15/1.png",
    },
    {
      id: "rice",
      word: "rice",
      translate: "рис",
      img: "img/4-l15/2.jpg",
    },
    {
      id: "cabbage",
      word: "cabbage",
      translate: "капуста",
      img: "img/4-l15/3.jpg",
    },
    {
      id: "steak",
      word: "steak",
      translate: "стейк",
      img: "img/4-l15/4.jpg",
    },
    {
      id: "peas",
      word: "peas",
      translate: "горох",
      img: "img/4-l15/5.jpg",
    },
  ],
  17: [
    {
      id: "rescue",
      word: "rescue",
      translate: "порятунок",
      img: "img/4-l17/1.jpg",
    },
    {
      id: "scarf",
      word: "scarf",
      translate: "шарф",
      img: "img/4-l17/2.jpg",
    },
    {
      id: "glove",
      word: "glove",
      translate: "рукавичка",
      img: "img/4-l17/3.png",
    },
    {
      id: "jacket",
      word: "jacket",
      translate: "куртка",
      img: "img/4-l17/4.jpg",
    },
    {
      id: "belt",
      word: "belt",
      translate: "пояс",
      img: "img/4-l17/5.jpg",
    },
    {
      id: "trainers",
      word: "trainers",
      translate: "кросівки",
      img: "img/4-l17/6.png",
    },
    {
      id: "tie",
      word: "tie",
      translate: "краватка",
      img: "img/4-l17/7.jpg",
    },
  ],
  18: [
    {
      id: "arrive",
      word: "arrive",
      translate: "прибувати",
      img: "img/4-l18/1.jpg",
    },
    {
      id: "leave",
      word: "leave",
      translate: "залишати",
      img: "img/4-l18/2.jpg",
    },
    {
      id: "start",
      word: "start",
      translate: "старт",
      img: "img/4-l18/3.gif",
    },
    {
      id: "lose",
      word: "lose",
      translate: "програти",
      img: "img/4-l18/4.gif",
    },
    {
      id: "bring",
      word: "bring",
      translate: "принести",
      img: "img/4-l18/5.gif",
    },
    {
      id: "finish",
      word: "finish",
      translate: "фініш",
      img: "img/4-l18/6.gif",
    },
  ],
  19: [
    {
      id: "bank",
      word: "bank",
      translate: "банк",
      img: "img/4-l19/1.gif",
    },
    {
      id: "post office",
      word: "post office",
      translate: "поштове відділення",
      img: "img/4-l19/2.gif",
    },
    {
      id: "send",
      word: "send",
      translate: "надіслати",
      img: "img/4-l19/3.gif",
    },
    {
      id: "find",
      word: "find",
      translate: "знайти",
      img: "img/4-l19/4.gif",
    },
    {
      id: "garage",
      word: "garage",
      translate: "гараж",
      img: "img/4-l19/5.gif",
    },
    {
      id: "hire",
      word: "hire",
      translate: "наймати",
      img: "img/4-l19/6.gif",
    },
  ],
  21: [
    {
      id: "van",
      word: "van",
      translate: "фургон",
      img: "img/4-l21/1.gif",
    },
    {
      id: "motobike",
      word: "motobike",
      translate: "мотоцикл",
      img: "img/4-l21/2.gif",
    },
    {
      id: "fire engine",
      word: "fire engine",
      translate: "пожежна машина",
      img: "img/4-l21/3.gif",
    },
    {
      id: "scooter",
      word: "scooter",
      translate: "скутер",
      img: "img/4-l21/4.gif",
    },
    {
      id: "helicopter",
      word: "helicopter",
      translate: "вертоліт",
      img: "img/4-l21/5.gif",
    },
  ],
  25: [
    {
      id: "join in",
      word: "join in",
      translate: "приєднатися",
      img: "img/4-l25/1.gif",
    },
    {
      id: "fancy dress",
      word: "fancy dress",
      translate: "маскарадний костюм",
      img: "img/4-l25/2.jpg",
    },
    {
      id: "costume",
      word: "costume",
      translate: "костюм",
      img: "img/4-l25/3.gif",
    },
    {
      id: "alien",
      word: "alien",
      translate: "прибулець",
      img: "img/4-l25/4.gif",
    },
    {
      id: "superhero",
      word: "superhero",
      translate: "супергерой",
      img: "img/4-l25/5.gif",
    },
    {
      id: "pop star",
      word: "pop star",
      translate: "поп зірка",
      img: "img/4-l25/6.gif",
    },
  ],
  24: [
    {
      id: "palace",
      word: "palace",
      translate: "палац",
      img: "img/4-lprince/1.png",
    },
    {
      id: "poor",
      word: "poor",
      translate: "бідний",
      img: "img/4-lprince/1.jpg",
    },
    {
      id: "begged",
      word: "begged",
      translate: "благав",
      img: "img/4-lprince/7.jpg",
    },
    {
      id: "gates",
      word: "gates",
      translate: "ворота",
      img: "img/4-lprince/3.jpg",
    },
    {
      id: "rich",
      word: "rich",
      translate: "багатий",
      img: "img/4-lprince/1-1.jpg",
    },
    {
      id: "servant",
      word: "servant",
      translate: "слуга",
      img: "img/4-lprince/9.jpg",
    },
    {
      id: "pauper",
      word: "pauper",
      translate: "жебрак",
      img: "img/4-lprince/9.png",
    },
  ],
  26: [
    {
      id: "ice scating",
      word: "ice scating",
      translate: "катання на ковзанах",
      img: "img/4-l26/1.gif",
    },
    {
      id: "surfing",
      word: "surfing",
      translate: "серфінг",
      img: "img/4-l26/2.gif",
    },
    {
      id: "skateboarding",
      word: "skateboarding",
      translate: "скейтбординг",
      img: "img/4-l26/3.gif",
    },
    {
      id: "rock climbing",
      word: "rock climbing",
      translate: "скелелазіння",
      img: "img/4-l26/4.gif",
    },
    {
      id: "cycling",
      word: "cycling",
      translate: "їзда на велосипеді",
      img: "img/4-l26/5.gif",
    },
    {
      id: "fishing",
      word: "fishing",
      translate: "риболовля",
      img: "img/4-l26/6.gif",
    },
  ],
  27: [
    {
      id: "use",
      word: "use",
      translate: "використання",
      img: "img/4-l27/1.gif",
    },
    {
      id: "escape",
      word: "escape",
      translate: "втеча",
      img: "img/4-l27/2.gif",
    },
    {
      id: "reach",
      word: "reach",
      translate: "досягти",
      img: "img/4-l27/3.gif",
    },
    {
      id: "borrow",
      word: "borrow",
      translate: "позичати",
      img: "img/4-l27/4.gif",
    },
    {
      id: "hold",
      word: "hold",
      translate: "тримати",
      img: "img/4-l27/5.gif",
    },
  ],
  29: [
    {
      id: "knock over",
      word: "knock over",
      translate: "перекинути",
      img: "img/4-l29/1.gif",
    },
    {
      id: "lamp",
      word: "lamp",
      translate: "лампа",
      img: "img/4-l29/2.gif",
    },
    {
      id: "curtain",
      word: "curtain",
      translate: "занавіска",
      img: "img/4-l29/3.gif",
    },
    {
      id: "rug",
      word: "rug",
      translate: "килимок",
      img: "img/4-l29/4.png",
    },
    {
      id: "sofa",
      word: "sofa",
      translate: "диван",
      img: "img/4-l29/5.gif",
    },
    {
      id: "cushion",
      word: "cushion",
      translate: "подушка",
      img: "img/4-l29/6.gif",
    },
    {
      id: "prison",
      word: "prison",
      translate: "тюрма",
      img: "img/4-l29/7.gif",
    },
  ],
  30: [
    {
      id: "plan",
      word: "plan",
      translate: "план",
      img: "img/4-l30/1.gif",
    },
    {
      id: "picnic",
      word: "picnic",
      translate: "пікнік",
      img: "img/4-l30/2.gif",
    },
    {
      id: "invitation",
      word: "invitation",
      translate: "запрошення",
      img: "img/4-l30/3.gif",
    },
    {
      id: "banner",
      word: "banner",
      translate: "банер",
      img: "img/4-l30/4.gif",
    },
  ],
  31: [
    {
      id: "rare",
      word: "rare",
      translate: "рідкісний",
      img: "img/4-l31/1.gif",
    },
    {
      id: "robber",
      word: "robber",
      translate: "грабіжник",
      img: "img/4-l31/2.gif",
    },
    {
      id: "steal",
      word: "steal",
      translate: "крадіжка",
      img: "img/4-l30/3.gif",
    },
    {
      id: "jewellery",
      word: "jewellery",
      translate: "ювелірні вироби",
      img: "img/4-l31/4.jpg",
    },
    {
      id: "valuable",
      word: "valuable",
      translate: "цінний",
      img: "img/4-l31/5.gif",
    },
    {
      id: "painting",
      word: "painting",
      translate: "живопис",
      img: "img/4-l31/6.gif",
    },
    {
      id: "diamond",
      word: "diamond",
      translate: "діаматнт",
      img: "img/4-l31/7.gif",
    },
  ],
  33: [
    {
      id: "disappear",
      word: "disappear",
      translate: "зникнути",
      img: "img/4-l33/1.gif",
    },
    {
      id: "explain",
      word: "explain",
      translate: "пояснювати",
      img: "img/4-l33/2.gif",
    },
    {
      id: "return",
      word: "return",
      translate: "повернення",
      img: "img/4-l33/3.gif",
    },
    {
      id: "hot air balloon",
      word: "hot air balloon",
      translate: "повітряна куля",
      img: "img/4-l33/4.gif",
    },
    {
      id: "trip",
      word: "trip",
      translate: "подорож",
      img: "img/4-l33/5.gif",
    },
  ],
  34: [
    {
      id: "horse riding",
      word: "horse riding",
      translate: "верхова їзда",
      img: "img/4-l34/1.gif",
    },
    {
      id: "camping",
      word: "camping",
      translate: "життя в таборі",
      img: "img/4-l34/2.gif",
    },
    {
      id: "сanoeing",
      word: "сanoeing",
      translate: "катання на каное",
      img: "img/4-l34/3.gif",
    },
    {
      id: "Chinese",
      word: "Chinese",
      translate: "Китай",
      img: "img/4-l34/4.gif",
    },
    {
      id: "restaurant",
      word: "restaurant",
      translate: "ресторан",
      img: "img/4-l34/5.gif",
    },
  ],
  35: [
    {
      id: "brush",
      word: "brush",
      translate: "кисть",
      img: "img/4-l35/1.gif",
    },
    {
      id: "polish",
      word: "polish",
      translate: "полірувати",
      img: "img/4-l35/2.gif",
    },
    {
      id: "сhange",
      word: "сhange",
      translate: "змінити",
      img: "img/4-l35/3.gif",
    },
  ],
};
